# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo_title
subtitle: this is subtitle
description: my first blogs
keywords: blogs, hexo  # 站点描述，给搜索引擎看的, 半角逗号分开
author: AugF
email: wangyunpan@outlook.com
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://github.com/Augf # 网址
root: /
permalink: :year/:month/:day/:title/  # 文章链接的格式
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags 
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:   # 分类别名
tag_map:  # tag别名

# Server # 本地服务器
port: 4000
server_ip: localhost # IP地址
logger: false
logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10  # 每页展示文章数
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next # 主题

# Deployment # 部署，将lmintlcx改成用户名
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/AugF/augf.github.io.git
  branch: master

# hexo-theme-next Config
# disqus_shortname: AugF's_disqus

menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories

social:
  Github: http://github.com/AugF
  Twitter: http://www.baidu.com
  微博: http://www.baidu.com
  知乎: http://www.baidu.com

social_icons:
  enable: true
  # Icon Mappings
  # # http://fontawesome.io/cheatsheet/
  Github: github
  Twitter: twitter
  微博: weibo
  知乎: zhihu

rss: 

# Favicon 图标
favicon: /favicon.ico

# Avatar 头像 next/source/images/
avatar: /images/default_avatar.png

# Code highlight theme
highlight_theme: normal

# Fancybox for image gallery
fancybox: true

# Specify the date when the site was setup
since: 2019

search:
  path: search.xml
  field: post
  format: html
  limit: 10000
 
livere_uid: MTiAyMC80NjU1Mi8yMzA2Mg==

reward_comment: test reward_comment 
wechatpay:
alipay: 
